# Multi-stage build для оптимизации размера образа
FROM golang:1.25 AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN apt-get update && apt-get upgrade -y && go mod download
RUN go mod download
RUN go mod verify
COPY . .
RUN go mod tidy
RUN make build_app

# Финальный образ
FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /build/app/bin/server ./bin/server
COPY --from=builder /build/env_docker/.env .
COPY --from=builder /build/public/ /app/public
EXPOSE 3000
CMD ["/app/bin/server"]